---
- name: Установка Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Распаковка Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/node_exporter-1.8.2.linux-amd64/node_exporter

- name: Создание симлинка для Node Exporter
  file:
    src: /usr/local/bin/node_exporter-1.8.2.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    state: link

- name: Создание systemd сервиса для Node Exporter
  copy:
    dest: /etc/systemd/system/node-exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      User=nobody
      ExecStart=/usr/local/bin/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Запуск Node Exporter
  systemd:
    name: node-exporter
    state: started
    enabled: yes
# tasks file for node-exporter
